# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558353ce529796de287f74d4dcb277b6ebaedc34cf233422728a6c7b45a2628c88e2fe2c0d704cac95c64d29385c9bc3de0ea2d054cfdf741ab2dc94a92de143

test:
  secret_key_base: fe485aab1c82844c3df7ba1fda67651128e4b998eb42ed6488ea996c4cbaeb6e91689c07a3b829de4c61d9f5c5225f4f8ab66ea43375769e6d6bde6b13201c61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
